/* NEN WORLD — Admin Config File
   This file is generated by admin.html
   Place it in the same folder as index.html
   It will automatically apply your admin panel customizations */
window.NEN_CONFIG = null;
