/* NEN ADMIN CONFIG — auto-generated */
window.NEN_CONFIG = {
  "fields": {
    "hero_badge_en": "World of Nen — Interactive Guide",
    "hero_badge_ar": "عالم النين — دليل تفاعلي",
    "hero_title_en": "World of Nen",
    "hero_title_ar": "عالم النين",
    "hero_sub_en": "The art of manipulating life energy — aura — to transcend human limits. Discover the most complex power system in anime.",
    "hero_sub_ar": "فن التحكم في طاقة الحياة — الأورا — لتجاوز الحدود البشرية. اكتشف أعقد نظام قوى في عالم الأنمي.",
    "hero_scroll_en": "↓ Scroll to explore ↓",
    "hero_scroll_ar": "↓ اسحب لاستكشاف ↓",
    "logo_width": "clamp(240px,45vw,520px)",
    "s_whatnen_en": "What is Nen?",
    "s_whatnen_ar": "ما هو النين؟",
    "s_whatnen_sub_en": "念 — The Art of Aura",
    "s_whatnen_sub_ar": "念 — فن الأورا",
    "s_principles_en": "The Four Major Principles",
    "s_principles_ar": "المبادئ الأربعة الرئيسية",
    "s_body_en": "Techniques Visualized on the Body",
    "s_body_ar": "التقنيات مُجسَّدة على الجسم",
    "s_types_en": "The Six Nen Types",
    "s_types_ar": "أنواع النين الستة",
    "s_restrict_en": "Restrictions & Vows",
    "s_restrict_ar": "القيد والنذر",
    "bannerEnabled": true,
    "bannerTextEn": "This website is experimental and under construction — we apologize for any errors in the site or the information!",
    "bannerTextAr": "هذا الموقع تجريبي وتحت الإنشاء - نأسف لأي خطأ في الموقع والمعلومات!",
    "footer_name_en": "World of Nen",
    "footer_name_ar": "عالم النين",
    "footer_tag_en": "Hunter × Hunter Interactive Guide",
    "footer_tag_ar": "دليل هنتر × هنتر التفاعلي",
    "footer_credit_en": "Based on Hunter × Hunter by Yoshihiro Togashi",
    "footer_credit_ar": "مستند إلى هنتر × هنتر بقلم يوشيهيرو توغاشي",
    "type_enhancer_nameEn": "Enhancer",
    "type_enhancer_nameAr": "المعزز",
    "type_enhancer_descEn": "The most straightforward and powerful type. Enhancers boost their own physical capabilities to superhuman levels.",
    "type_enhancer_descAr": "النوع الأكثر مباشرةً وقوةً. يعززون قدراتهم الجسدية إلى مستويات فوق بشرية.",
    "type_enhancer_waterEn": "Water volume increases",
    "type_enhancer_waterAr": "يزداد حجم الماء",
    "type_enhancer_personEn": "Simple, determined, and focused on their goals",
    "type_enhancer_personAr": "بسيطون، عزيمة قوية، مركزون على أهدافهم",
    "type_enhancer_char1": "Gon Freecss",
    "type_enhancer_char1En": "Jajanken (Rock-Paper-Scissors)",
    "type_enhancer_char1Ar": "جاجانكين (حجر ورق مقص)",
    "type_enhancer_char2": "Uvogin",
    "type_enhancer_char2En": "Enhanced physical destruction",
    "type_enhancer_char2Ar": "تدمير جسدي معزز",
    "type_transmuter_nameEn": "Transmuter",
    "type_transmuter_nameAr": "المحول",
    "type_transmuter_descEn": "Transmuters alter the properties of their aura to mimic other substances — electricity, fire, or water.",
    "type_transmuter_descAr": "يغيرون خصائص أوراهم ليحاكوا مواد أخرى — كهرباء، نار، أو ماء.",
    "type_transmuter_waterEn": "Water changes taste",
    "type_transmuter_waterAr": "يتغير طعم الماء",
    "type_transmuter_personEn": "Whimsical, unpredictable, prone to deception",
    "type_transmuter_personAr": "متقلبون، غير متوقعين، يميلون للخداع",
    "type_transmuter_char1": "Killua Zoldyck",
    "type_transmuter_char1En": "Godspeed — lightning electricity",
    "type_transmuter_char1Ar": "سرعة الإله — كهرباء",
    "type_transmuter_char2": "Hisoka",
    "type_transmuter_char2En": "Bungee Gum — elastic sticky aura",
    "type_transmuter_char2Ar": "بنجي غام — أورا مرنة ولزجة",
    "type_emitter_nameEn": "Emitter",
    "type_emitter_nameAr": "الباعث",
    "type_emitter_descEn": "Emitters project their aura beyond their body, launching it as projectiles or maintaining it at a distance.",
    "type_emitter_descAr": "يطلقون أوراهم خارج أجسامهم ويحافظون عليها عن بُعد.",
    "type_emitter_waterEn": "Water changes color",
    "type_emitter_waterAr": "يتغير لون الماء",
    "type_emitter_personEn": "Impatient, hot-headed, volatile and impulsive",
    "type_emitter_personAr": "غير صبورين، متهورون، متفجرون وانفعاليون",
    "type_emitter_char1": "Leorio Paradinight",
    "type_emitter_char1En": "Long-range aura punch",
    "type_emitter_char1Ar": "لكمة أورا بعيدة المدى",
    "type_emitter_char2": "Franklin Bordeau",
    "type_emitter_char2En": "Double Machine Gun — aura bullets",
    "type_emitter_char2Ar": "رشاش مزدوج — رصاصات أورا",
    "type_conjurer_nameEn": "Conjurer",
    "type_conjurer_nameAr": "المجسد",
    "type_conjurer_descEn": "Conjurers materialize physical objects from their aura. These objects are real and can interact with the world.",
    "type_conjurer_descAr": "يجسدون أشياء مادية من أوراهم. هذه الأشياء حقيقية وتتفاعل مع العالم.",
    "type_conjurer_waterEn": "Impurities appear in water",
    "type_conjurer_waterAr": "تظهر شوائب في الماء",
    "type_conjurer_personEn": "High-strung, overly cautious, stoic, analytical",
    "type_conjurer_personAr": "متوترون، حذرون جداً، متزنون، تحليليون",
    "type_conjurer_char1": "Kurapika",
    "type_conjurer_char1En": "Emperor Time — holy chains",
    "type_conjurer_char1Ar": "وقت الإمبراطور — سلاسل مقدسة",
    "type_conjurer_char2": "Kortopi",
    "type_conjurer_char2En": "Gallery Fake — perfect object copies",
    "type_conjurer_char2Ar": "معرض المزيف — نسخ مثالية من الأشياء",
    "type_manipulator_nameEn": "Manipulator",
    "type_manipulator_nameAr": "المتلاعب",
    "type_manipulator_descEn": "Manipulators control living beings or objects with their aura. The harder the condition, the greater the control.",
    "type_manipulator_descAr": "يتلاعبون بالكائنات الحية أو الأشياء بأوراهم. كلما صعب الشرط، كانت درجة السيطرة أكبر.",
    "type_manipulator_waterEn": "Leaf moves on the water",
    "type_manipulator_waterAr": "تتحرك الورقة على الماء",
    "type_manipulator_personEn": "Argumentative, logical, and calculative",
    "type_manipulator_personAr": "جدليون، منطقيون، حسابيون",
    "type_manipulator_char1": "Illumi Zoldyck",
    "type_manipulator_char1En": "Control via needles in others",
    "type_manipulator_char1Ar": "التحكم عبر إبر في الآخرين",
    "type_manipulator_char2": "Neferpitou",
    "type_manipulator_char2En": "Doctor Blythe — puppet surgery",
    "type_manipulator_char2Ar": "طبيب بلايس — جراحة الدمى",
    "type_specialist_nameEn": "Specialist",
    "type_specialist_nameAr": "المتخصص",
    "type_specialist_descEn": "The rarest and most mysterious type. Specialists have abilities that don't fit any other category.",
    "type_specialist_descAr": "النوع الأنادر والأكثر غموضاً. للمتخصصين قدرات لا تنتمي لأي فئة أخرى.",
    "type_specialist_waterEn": "A completely unique reaction",
    "type_specialist_waterAr": "رد فعل مختلف تماماً وفريد",
    "type_specialist_personEn": "Independent, charismatic, and unconventional",
    "type_specialist_personAr": "مستقلون، كاريزماتيون، غير تقليديين",
    "type_specialist_char1": "Chrollo Lucilfer",
    "type_specialist_char1En": "Skill Hunter — steals others' abilities",
    "type_specialist_char1Ar": "صائد المهارات — يسرق قدرات الآخرين",
    "type_specialist_char2": "Neon Nostrade",
    "type_specialist_char2En": "Lovely Ghost Writer — future prophecy",
    "type_specialist_char2Ar": "كاتبة الأشباح — التنبؤ بالمستقبل"
  },
  "footerLinks": [],
  "bannerColor": "#f0c060",
  "linksHtml": "",
  "bannerHtml": "<div id=\"siteBanner\" style=\"background:#f0c06018;border-bottom:1px solid #f0c06044;padding:.6rem 2rem;text-align:center;font-size:.88rem;color:#f0c060\">\n        <span class=\"en-only\">This website is experimental and under construction — we apologize for any errors in the site or the information!</span>\n        <span class=\"ar-only\">هذا الموقع تجريبي وتحت الإنشاء - نأسف لأي خطأ في الموقع والمعلومات!</span>\n      </div>",
  "logoB64": null
};