/* NEN ADMIN CONFIG */
window.NEN_CONFIG = {
  "fields": {
    "hero_badge_en": "World of Nen — Interactive Guide",
    "hero_badge_ar": "عالم النين — دليل تفاعلي",
    "hero_title_en": "World of Nen",
    "hero_title_ar": "عـالـم الـنـيـن",
    "hero_sub_en": "The art of manipulating life energy — aura — to transcend human limits. Discover the most complex power system in anime.",
    "hero_sub_ar": "فن التحكم في طاقة الحياة — الأورا — لتجاوز الحدود البشرية. اكتشف أعقد نظام قوى في عالم الأنمي.",
    "hero_scroll_en": "↓ Scroll to explore ↓",
    "hero_scroll_ar": "↓ اسحب لإستكشاف عالم النين ↓",
    "bannerEnabled": true,
    "bannerTextEn": "This website is experimental and under construction — we apologize for any errors in the site or the information!",
    "bannerTextAr": "هذا الموقع تجريبي وتحت الإنشاء - نأسف لأي خطأ في الموقع والمعلومات!",
    "ft_name_en": "World of Nen",
    "ft_name_ar": "عالم النين",
    "ft_tag_en": "Hunter × Hunter Interactive Guide",
    "ft_tag_ar": "دليل هنتر × هنتر التفاعلي",
    "ft_cr_en": "Based on Hunter × Hunter by Yoshihiro Togashi",
    "ft_cr_ar": "مستند إلى هنتر × هنتر بقلم يوشيهيرو توغاشي",
    "s_whatnen_en": "What is Nen?",
    "s_whatnen_ar": "ما هو النين؟",
    "s_principles_en": "The Four Major Principles",
    "s_principles_ar": "المبادئ الأربعة الرئيسية",
    "s_adv_tech_en": "Advanced Techniques",
    "s_adv_tech_ar": "التقنيات المتقدمة",
    "s_body_tech_en": "Techniques Visualized on the Body",
    "s_body_tech_ar": "التقنيات مُجسَّدة على الجسم",
    "s_compat_en": "Nen Type Compatibility Chart",
    "s_compat_ar": "جدول توافق أنواع النين",
    "s_types_en": "The Six Nen Types",
    "s_types_ar": "أنواع النين الستة",
    "s_water_en": "Water Divination Test",
    "s_water_ar": "اختبار تكهن الماء",
    "s_restrict_en": "Restrictions & Vows",
    "s_restrict_ar": "القيود والنذور",
    "s_groups_en": "Groups & Factions",
    "s_groups_ar": "المجموعات والفصائل",
    "s_arcs_en": "Story Arcs",
    "s_arcs_ar": "مسارات القصة",
    "s_worldmap_en": "World Map",
    "s_worldmap_ar": "خريطة العالم",
    "s_quiz_en": "Test Your Nen Knowledge",
    "s_quiz_ar": "اختبر معرفتك بالنين",
    "nt_enhancer_nameEn": "Enhancer",
    "nt_enhancer_nameAr": "المعزز",
    "nt_enhancer_descEn": "",
    "nt_enhancer_descAr": "",
    "nt_enhancer_waterEn": "",
    "nt_enhancer_waterAr": "",
    "nt_enhancer_personEn": "",
    "nt_enhancer_personAr": "",
    "nt-en-c1_nameEn": "Gon Freecss",
    "nt-en-c1_nameAr": "غون فريكس",
    "nt-en-c1_abilityEn": "",
    "nt-en-c1_abilityAr": "",
    "nt-en-c2_nameEn": "Uvogin",
    "nt-en-c2_nameAr": "أوفوغين",
    "nt-en-c2_abilityEn": "",
    "nt-en-c2_abilityAr": "",
    "nt-en-c3_nameEn": "Meruem",
    "nt-en-c3_nameAr": "ميروم",
    "nt-en-c3_abilityEn": "",
    "nt-en-c3_abilityAr": "",
    "nt_transmuter_nameEn": "Transmuter",
    "nt_transmuter_nameAr": "المحول",
    "nt_transmuter_descEn": "",
    "nt_transmuter_descAr": "",
    "nt_transmuter_waterEn": "",
    "nt_transmuter_waterAr": "",
    "nt_transmuter_personEn": "",
    "nt_transmuter_personAr": "",
    "nt-tr-c1_nameEn": "Killua Zoldyck",
    "nt-tr-c1_nameAr": "كيلوا زولديك",
    "nt-tr-c1_abilityEn": "",
    "nt-tr-c1_abilityAr": "",
    "nt-tr-c2_nameEn": "Hisoka",
    "nt-tr-c2_nameAr": "هيسوكا",
    "nt-tr-c2_abilityEn": "",
    "nt-tr-c2_abilityAr": "",
    "nt_emitter_nameEn": "Emitter",
    "nt_emitter_nameAr": "الباعث",
    "nt_emitter_descEn": "",
    "nt_emitter_descAr": "",
    "nt_emitter_waterEn": "",
    "nt_emitter_waterAr": "",
    "nt_emitter_personEn": "",
    "nt_emitter_personAr": "",
    "nt-em-c1_nameEn": "Leorio",
    "nt-em-c1_nameAr": "ليوريو",
    "nt-em-c1_abilityEn": "",
    "nt-em-c1_abilityAr": "",
    "nt-em-c2_nameEn": "Franklin",
    "nt-em-c2_nameAr": "فرانكلين",
    "nt-em-c2_abilityEn": "",
    "nt-em-c2_abilityAr": "",
    "nt_conjurer_nameEn": "Conjurer",
    "nt_conjurer_nameAr": "المجسد",
    "nt_conjurer_descEn": "",
    "nt_conjurer_descAr": "",
    "nt_conjurer_waterEn": "",
    "nt_conjurer_waterAr": "",
    "nt_conjurer_personEn": "",
    "nt_conjurer_personAr": "",
    "nt-co-c1_nameEn": "Kurapika",
    "nt-co-c1_nameAr": "كوراباكا",
    "nt-co-c1_abilityEn": "",
    "nt-co-c1_abilityAr": "",
    "nt-co-c2_nameEn": "Kortopi",
    "nt-co-c2_nameAr": "كورتوبي",
    "nt-co-c2_abilityEn": "",
    "nt-co-c2_abilityAr": "",
    "nt_manipulator_nameEn": "Manipulator",
    "nt_manipulator_nameAr": "المتلاعب",
    "nt_manipulator_descEn": "",
    "nt_manipulator_descAr": "",
    "nt_manipulator_waterEn": "",
    "nt_manipulator_waterAr": "",
    "nt_manipulator_personEn": "",
    "nt_manipulator_personAr": "",
    "nt-ma-c1_nameEn": "Illumi Zoldyck",
    "nt-ma-c1_nameAr": "إيلومي زولديك",
    "nt-ma-c1_abilityEn": "",
    "nt-ma-c1_abilityAr": "",
    "nt-ma-c2_nameEn": "Neferpitou",
    "nt-ma-c2_nameAr": "نيفيربيتو",
    "nt-ma-c2_abilityEn": "",
    "nt-ma-c2_abilityAr": "",
    "nt_specialist_nameEn": "Specialist",
    "nt_specialist_nameAr": "المتخصص",
    "nt_specialist_descEn": "",
    "nt_specialist_descAr": "",
    "nt_specialist_waterEn": "",
    "nt_specialist_waterAr": "",
    "nt_specialist_personEn": "",
    "nt_specialist_personAr": "",
    "nt-sp-c1_nameEn": "Chrollo Lucilfer",
    "nt-sp-c1_nameAr": "كرولو لوسيلفر",
    "nt-sp-c1_abilityEn": "",
    "nt-sp-c1_abilityAr": "",
    "nt-sp-c2_nameEn": "Neon Nostrade",
    "nt-sp-c2_nameAr": "نيون نوسترادي",
    "nt-sp-c2_abilityEn": "",
    "nt-sp-c2_abilityAr": ""
  },
  "footerLinks": [],
  "bannerColor": "#f0c060",
  "linksHtml": "",
  "bannerHtml": "<div id=\"siteBanner\" style=\"background:#f0c06022;border-bottom:2px solid #f0c06066;padding:.7rem 2rem;text-align:center;font-size:.9rem;color:#f0c060;font-weight:600;position:relative;z-index:99\">📢 <span class=\"en-only\">This website is experimental and under construction — we apologize for any errors in the site or the information!</span><span class=\"ar-only\">هذا الموقع تجريبي وتحت الإنشاء - نأسف لأي خطأ في الموقع والمعلومات!</span></div>",
  "logoB64": null,
  "avatars": {},
  "quizBank": {
    "en": [],
    "ar": []
  },
  "savedAt": "2026-03-27T07:35:58.836Z"
};